version: "3.9"

services:
  app:
    build: app/
    env_file:
      - .env.dev
    restart: unless-stopped
    command: "python main.py --env dev"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    healthcheck:
      test:
        ["CMD-SHELL", "wget localhost:8000/api/health -q -O - > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - tinycdn_dev

networks:
  tinycdn_dev:
