version: "3.9"

services:
  app:
    build: app/
    env_file:
      - .env
    command: "python main.py --env prod"
    ports:
      - 8000:8000
    healthcheck:
      test:
        ["CMD-SHELL", "wget localhost:8000/api/health -q -O - > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - tinycdn

networks:
  tinycdn:
